exclude: "^docs/|/migrations/^.js.map|app/assets|static"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: (^tests/fixtures/|^output/|app/assets/img)
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--fail-under=0, --verbose]

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        language_version: python3.11
        args: [-s, "B101,B311,B303,B105,B104,B106,B113"]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
        stages: [pre-push]
      - id: poetry-lock
        stages: [pre-push]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-isort]
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.4.0
    hooks:
      - id: autoflake8
        args: ["--in-place", "--remove-unused-variable"]

  - repo: local
    hooks:
      - id: check-bash-syntax
        name: Check Shell scripts syntax correctness
        language: system
        entry: bash -n
        files: \.sh$

  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       language: system
  #       entry: bash -c "mypy app"

  - repo: local
    hooks:
      - id: update-requirements-txt
        name: update-requirements-txt
        description: "Generate requirements.txt based on poetry.lock"
        entry: poetry-requirements.sh
        language: script
        pass_filenames: false

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint --ignore=.pylintrc
        language: system
        types: [python]
        args: ["-rn", "-sn"]

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       stages: [pre-commit]
  #       language: system
  #       entry: pytest --cov-fail-under=80  --cov-report term-missing --cov=domain test/
  #       types: [python]
  #       pass_filenames: false
  #       verbose: true

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false

default_language_version:
  python: python3.11
