[build-system]
requires = ["setuptools==80.9.0","requests==2.32.5","requests-oauthlib==2.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "NetSuite-Connector"
version = "0.3.3"
authors = [
  { name="Marcos Lopez", email="merick16@gmail.com" },
]
description = "NetSuite Connector"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.5",
    "requests-oauthlib>=2.0.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
netsuite-mcp = "NetSuite_Connector.__main__:main"

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "requests-mock>=1.12.1"
]

[project.urls]
"Homepage" = "https://github.com/IngMarcosLopez/NetSuite-Connector"
"Bug Tracker" = "https://github.com/IngMarcosLopez/NetSuite-Connector/issues"

[tool.poetry.dependencies]
requests = "^2.32.5"
requests-oauthlib = "^2.0.0"
setuptools = "^80.9.0"
wheel = "^0.45.1"
pytest = "^9.0.2"
pytest-cov = "^7.0.0"
pytest-mock = "^3.15.1"
requests-mock = "^1.12.1"
